### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Bakersfieldmods** [GiantDwarf01/Pokemon-Rivals#2]
**General Scripting requests**

- [x] Any cards in a player's mailbox should be automatically drawn to their hand at the start of their turn.

- [x] The town map item needs to be accounted for when exploring. (When the player has the Town Map on the item pad and presses the tile spawn button to reveal a new tile, It should draw two tiles instead of one and the player can choose which to keep. 
![image](https://user-images.githubusercontent.com/34212182/33921360-ee5339ce-df88-11e7-8c39-bf991460dad8.png)
Like the above, when the arrow is pressed two random tiles from the pool come out. They are 0.4 scale. Instead of the spawn button in the middle it should say choose. Then once one is chosen that one gets placed normally and the other one goes back into the pool and the pool is shuffled)
- [x] When Gyms are defeated, The badge should be displayed on that player's board automatically and the Reputation points should be added to that players counter, if possible.
- [x] Any way to get rid of the Pokedex cards popping up in the middle of the table when players are cycling through the dex. (If it is possible to move this animation below the table or off to the side so that it is not popping up in the middle of everyone;s view. 

- [x] Whenever a player earns reputation points there should be an announcement that "PLAYERNAME earned X RP"

- [x] Once the above script is implemented, defeating an NPC trainer should automatically add +1 to the Trainer counter. 

- [x] NPC Trainers should have auto scripting similarly to how GYM leaders do. When a player places their piece on the arrow that is on the square adjacent to the trainer, it is an auto encounter. The arrow button should also be clickable so that a player can choose to battle the trainer if the player is next to the trainer but not in front of them. (Arrow on the square in front of them. If it is easier you can make the same square have the button for all of them and I can rotate the model to match the facing)

- [x] Also is it possible to get the Pokedex cards to pop up at the right orientation instead of spawning horizontal and then rotating 90 degrees.

- [x] Need to make it so that other players cannot click your buttons. (For example, if I am battling a GYM, and another player is playing the role of the GYM leader, if they click my "KO!" button it gives their active pokemon the XP and stops my GYM Battle)
- [x] Cave Exit doesnt have tile spawn arrow
- [x] Need a force evolution button or command so that if your evolution step is missed you can trigger the evolution manually. (maybe something like "!evolve 1" to force evolve the Pokemon in the first slot of your bench)
- [x] Minor request: When the trainer card is chosen, it is scaled up a little bit to fit the size of the trainer pad. There should only be a slight trim around the edge where you see the trainer pad. 

- [x] After a Player choose a trainer, the trainer card should grow slightly bigger to fill the Trainer Pad. (It will look better)

**Achievements**

- [x] When the player scores the achievement (places it on their completed achievements pad) they get the appropriate amount of reputation points added to their counter.

- [x] When the Collector and Teamster achievements are scored and placed on the completed achievement pad, it grants that player the rewards.

**Quests**

- [x] The three scientist's on the board should have a quest template on them that makes it when you place an item on them, you get a Pokemon. (This is so that when you acquire a fossil and bring it to them, you can drop the card on to them, it disappears and the appropriate Pokemon card is placed in your hand. I place for a few quests to also follow this same template format)

**Trainer abilities in need of scripting** 

- [x] Bug Catcher's trainer ability and Type Preference Bonus (For the trainer ability, I will make specific versions of the fully evolved bug Pokemon with the added damage stat on the card. The script will just need to pull from a separate table if the Bug Catcher card is detected on the Trainer Pad)

- [x] Burglar's second ability (Once the player defeats an NPC, one of the Pokemon will be chosen at random and will pop up on the players side with a board that says "Steal?" and a button that says "Yes" or "No")

- [x] Psychic's first ability (When the Psychic player makes an encounter check and gets an item, they have a chance at drawing a second item. Start with 50% chance. If the Psychic does end up drawing two items it should print "A second item appears in the Psychic's hand")

- [x] Firebreather only gets 4 bench slots. Need the script to remove the rightmost two bench pads if the player is playing Firebreather

- [x] Both of Ruin Maniac's abilities (For the first ability, if the Ruin Maniac player encounters an item, they should also automatically draw a random item from the discard pile and the game should print "PLAYERNAME dug up an item." For the second ability, I want there to be a pop-up button that asks if you want to "Bypass Encounter?"

**Command Requests**

- [x] !encounter (force an item or Pokemon encounter)
- [x] !dropin (If possible this would be a great command so that if you have either a quitter or a spare spot and are past the startup process but early enough that someone can drop in to play this command would pull up the trainer board for start up for that player so that they can get a trainer and starter selected)
- [x] !addxp, !removexp, !setxp (To set the XP value of one of your Pokemon)

- [x] !spawn (card or object)

**Comment by GiantDwarf01** [comment]
DONE
